services:
  postgres:
    image: postgres:17
    container_name: elearning-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: elearning_identity
      POSTGRES_USER: elearning
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: